// Makes the sound effects from code, so there are no binary sources to
// track down, and writes them as data URIs into ../sounds.js. Howler plays
// a data URI without fetching anything, so sound works from a file:// page
// as well as from a server. Run: node dominion/tools/sfx.js
"use strict";
const fs = require("fs");
const path = require("path");
const RATE = 16000;

// A tiny deterministic noise source, so a rerun makes identical files.
let seed = 12345;
const noise = () => { seed = (seed * 1103515245 + 12345) & 0x7fffffff; return seed / 0x3fffffff - 1; };
const env = (t, a, d) => (t < a ? t / a : Math.exp(-(t - a) / d));

function render(seconds, fn) {
  const n = Math.floor(seconds * RATE), out = new Float32Array(n);
  for (let i = 0; i < n; i++) out[i] = fn(i / RATE);
  // Fade the last 10 ms so nothing clicks.
  for (let i = Math.max(0, n - 220); i < n; i++) out[i] *= (n - i) / 220;
  return out;
}
function wav(samples) {
  const b = Buffer.alloc(44 + samples.length * 2);
  b.write("RIFF", 0); b.writeUInt32LE(36 + samples.length * 2, 4); b.write("WAVE", 8);
  b.write("fmt ", 12); b.writeUInt32LE(16, 16); b.writeUInt16LE(1, 20); b.writeUInt16LE(1, 22);
  b.writeUInt32LE(RATE, 24); b.writeUInt32LE(RATE * 2, 28); b.writeUInt16LE(2, 32); b.writeUInt16LE(16, 34);
  b.write("data", 36); b.writeUInt32LE(samples.length * 2, 40);
  for (let i = 0; i < samples.length; i++) b.writeInt16LE(Math.round(Math.max(-1, Math.min(1, samples[i])) * 32000), 44 + i * 2);
  return b;
}
const sine = (f, t) => Math.sin(2 * Math.PI * f * t);
const tone = (f, t, a, d) => sine(f, t) * env(t, a, d);
// A one-pole low-pass over a noise stream, for whooshes and crackle.
function lowNoise(cut) { let y = 0; return () => { y += cut * (noise() - y); return y; }; }

const SOUNDS = {
  click: render(0.06, (t) => 0.35 * tone(1250, t, 0.002, 0.015)),
  lock: render(0.24, (t) => 0.4 * (t < 0.09 ? tone(660, t, 0.003, 0.04) : tone(990, t - 0.09, 0.003, 0.06))),
  launch: (() => { const n = lowNoise(0.08); return render(0.32, (t) => 0.9 * n() * env(t, 0.06, 0.08)); })(),
  capture: render(0.45, (t) => 0.3 * [523, 659, 784].reduce((s, f, i) => s + (t > i * 0.07 ? tone(f, t - i * 0.07, 0.004, 0.12) : 0), 0)),
  repulsed: render(0.26, (t) => 0.6 * sine(110 * (1 - t), t) * env(t, 0.004, 0.06)),
  clash: (() => { const n = lowNoise(0.35); return render(0.3, (t) => 0.7 * n() * env(t, 0.002, 0.05) * (0.6 + 0.4 * Math.sign(sine(31, t)))); })(),
  doomlock: render(0.9, (t) => 0.22 * sine(300 + 500 * t + 40 * sine(9, t), t) * env(t, 0.05, 0.5)),
  doomstar: (() => { const n = lowNoise(0.05); return render(1.4, (t) => 0.8 * (sine(55 - 20 * t, t) * env(t, 0.005, 0.35) + 0.8 * n() * env(t, 0.01, 0.4))); })(),
  score: render(0.75, (t) => 0.26 * [523, 659, 784, 1047].reduce((s, f, i) => s + (t > i * 0.11 ? tone(f, t - i * 0.11, 0.005, 0.2) : 0), 0)),
  law: render(0.42, (t) => 0.7 * ((t < 0.2 ? tone(180, t, 0.001, 0.025) : tone(160, t - 0.2, 0.001, 0.03)) + 0.3 * noise() * env(t % 0.2, 0.001, 0.008))),
  round: render(1.0, (t) => 0.25 * (tone(880, t, 0.003, 0.35) + 0.5 * tone(1320, t, 0.003, 0.25) + 0.25 * tone(1760, t, 0.003, 0.15)))
};

const lines = Object.keys(SOUNDS).map((k) => "  " + k + ": \"data:audio/wav;base64," + wav(SOUNDS[k]).toString("base64") + "\"");
const out = path.join(__dirname, "..", "sounds.js");
fs.writeFileSync(out, "// Generated by tools/sfx.js. Do not edit.\nwindow.DominionSounds = {\n" + lines.join(",\n") + "\n};\n");
console.log("wrote", Object.keys(SOUNDS).length, "sounds to", out, fs.statSync(out).size, "bytes");
